### ISSUE TITLE
Axis permalink broken

### ISSUE THREAD

**Issue by stefanoortisi** [furrio/meteor-stylus-multi#10]

**Comment by cryptoquick** [comment]
Thanks for catching this! I know the developer, I'll ask him about it. :smile_cat:

**Comment by cryptoquick** [comment]
I just heard back from @jenius, and it turns out, there's new documentation. This package has been updated to reflect that. Thanks for the attention to detail, and I appreciate the notification!

**Comment by jenius** [comment]
Sorry about that guys. Both the package and docs are much better now as well, if that helps. Old docs can still be found at http://v1.roots.cx/axis/ if you need em for some reason!
