### ISSUE TITLE
Package just hangs when extracting

### ISSUE THREAD

**Issue by Sandeep3005** [furrio/meteor-stylus-multi#13]
Hi there, running app on windows machine

I've tried adding the following package:
stolinski:stylus-multi

But its just hangs on Extracting stolinski:stylus-multi@1.4... /

I even left it overnight to run.

I'm using the latest version of meteor

Please, any help would be appreciated.

**Comment by T00mm** [comment]
Have the same problem, tried cleaning up the cache etc but nothing.

**Comment by cryptoquick** [comment]
The package indicated in the original post is not this package. Please contact that package's author.
