### ISSUE TITLE
Feature request: Alternative to import.styl naming

### ISSUE THREAD

**Issue by sbking** [furrio/meteor-stylus-multi#7]
When separating Meteor applications into separate component packages, it would be nice to be able to import component styles like this:

main.styl:

    @import 'packages/myComponent'

packages/myComponent/myComponent.styl:

    @import 'myModule1'
    @import 'myModule2'

packages/myComponent/myModule1/myModule1.styl:

    ...

Unfortunately, to make Meteor watch Stylus files without compiling them separately, we have to change those import directives to:

    @import 'packages/myComponent/myComponent.import'

and:

    @import 'myModule1/myModule1.import'
    @import 'myModule2/myModule2.import'

Perhaps the source handler plugin could detect a custom commented directive at the top of `.styl` files that can tell the plugin not to compile the file. That would allow the shorthand import notation. Something like:

packages/myComponent/myComponent.styl:

    //@import-only
    @import 'myModule1'

packages/myComponent/myModule1/myModule1.styl:

    //@import-only
    ...

**Comment by cryptoquick** [comment]
I'm still interested in a way to fix this issue. I might give it a shot now, too.

**Comment by cryptoquick** [comment]
This turned out to be a great idea. Let me know how this works for you. It's been added to `1.2.0`.
